version: "3.8"

services:
  reffinder:
    container_name: reffinder
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - 80:80
    volumes:
      - ./public:/var/www/html
    networks:
      - reffinder-network

networks:
    reffinder-network:
        driver: bridge
